# Generated by Django 4.1.7 on 2023-02-20 08:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_article_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body',
            field=ckeditor.fields.RichTextField(default='f'),
        ),
    ]
