# Generated by Django 4.1.6 on 2023-02-11 03:10

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='996', max_length=128, region=None, unique=True, verbose_name='Телефон номер'),
        ),
        migrations.AlterField(
            model_name='client',
            name='female',
            field=models.CharField(choices=[('0', 'Аял'), ('1', 'Эркек')], max_length=1),
        ),
    ]
