# Generated by Django 4.1.5 on 2023-02-15 08:28

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_phone_alter_client_female'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.doctor', verbose_name='Врач'),
        ),
        migrations.AlterField(
            model_name='client',
            name='female',
            field=models.CharField(choices=[('0', 'Аял'), ('1', 'Эркек')], max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+996', max_length=128, region=None, unique=True, verbose_name='Телефон номер'),
        ),
        migrations.AlterField(
            model_name='client',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.region', verbose_name='Регион'),
        ),
    ]
