# Generated by Django 4.1.7 on 2023-03-28 07:39

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_post_alter_client_doctor_alter_client_female_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Пост:'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Тема поста'),
        ),
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='Поля автоматически заполняется: ')),
                ('info', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Информация по отделении: ')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.region')),
            ],
            options={
                'verbose_name': 'Отделение',
                'verbose_name_plural': 'Отделении',
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(default=56, on_delete=django.db.models.deletion.CASCADE, to='client.departament'),
            preserve_default=False,
        ),
    ]
