# Generated by Django 4.1.7 on 2023-03-29 02:42

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_client_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя')),
                ('first_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('slug', models.SlugField(help_text='Поля автоматический заполняется!', unique=True)),
                ('img', models.ImageField(upload_to='media/photo_doc', verbose_name='Изображение врача: ')),
                ('experience', models.IntegerField(blank=True, verbose_name='Стаж: ')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(default='+996', max_length=128, region=None, verbose_name='Телефон номер')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.departament')),
            ],
            options={
                'verbose_name': 'Врачи',
                'verbose_name_plural': 'Врачи',
            },
        ),
        migrations.AlterField(
            model_name='client',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.doctor', verbose_name='Врач'),
        ),
        migrations.DeleteModel(
            name='DoctorUser',
        ),
    ]
